---
title: "About"
output: html_document
---

<style type="text/css">

           body {
           max-width:100%;
           padding:0;
           background-color: #FFFFFF;
           font-size: 14px;
           font-family: 'Source Sans Pro';
           }
           body, td {
           <!-- font-size: 13px; -->
           font-family: sans-serif;
           }
           .main-sidebar{ width: 230px; }
           h4 {
           font-size: 18px;
           }
           .main-sidebar{position:absolute;top:0;left:0;padding-top:50px;min-height:100%;width:230px;z-index:810;-webkit-transition:-webkit-transform .3s ease-in-out,width .3s ease-in-out;-moz-transition:-moz-transform .3s ease-in-out,width .3s ease-in-out;-o-transition:-o-transform .3s ease-in-out,width .3s ease-in-out;transition:transform .3s ease-in-out,width .3s ease-in-out}
           @media (min-width: 768px ) {
              .main-header .logo {
           width: 230px;
           }}
           @media (max-width:767px){.sidebar-open .content-wrapper,.sidebar-open .main-footer,.sidebar-open .right-side{-webkit-transform:translate(230px,0);-ms-transform:translate(230px,0);-o-transform:translate(230px,0);transform:translate(230px,0)}
           }
           .main-header .navbar{-webkit-transition:margin-left .3s ease-in-out;-o-transition:margin-left .3s ease-in-out;transition:margin-left .3s ease-in-out;margin-bottom:0;margin-left:230px;border:none;min-height:50px;border-radius:0}
           .main-header .logo{-webkit-transition:width .3s ease-in-out;-o-transition:width .3s ease-in-out;transition:width .3s ease-in-out;display:block;float:left;height:50px;font-size:20px;line-height:50px;text-align:center;width:230px;font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;padding:0 15px;font-weight:300;overflow:hidden}
           .control-sidebar,.control-sidebar-bg{top:0;right:-230px;width:230px;-webkit-transition:right .3s ease-in-out;-o-transition:right .3s ease-in-out;transition:right .3s ease-in-out}
           
</style>

# idiogramFISH - ShinyApp: Idiograms with Marks and Karyotype Indices

vignette: https://ferroao.gitlab.io/idiogramfishhelppages/

doi: 10.5281/zenodo.3579417

Public Repository: https://gitlab.com/ferroao/idiogramFISH

The left side menu of the page consists of:

* data.frame inputs
    + Load example
    + Chr. data data.frame
    + Mark Pos. data d.f.
    + Marks' Style

* Param. & idiogram
    + Parameters
    + Log
    + code

* About

# References

``` {r, echo=F, results="asis", message=F, warning=F}
library(bib2df)
invisible(tryCatch(lapply(list.files(pattern=".bib"), function(x) mybibdf <<- bib2df(x) ), error = function(e){cat("not found")} ) ) 
if(exists("mybibdf")) {
colnames(mybibdf)<-tolower(colnames(mybibdf))
mybibdf<-as.data.frame(mybibdf, stringsAsFactors=F)
for (i in 1:nrow(mybibdf)){
    for (j in 1:ncol(mybibdf)){
        mybibdf[[i,j]]<-paste0(unlist (mybibdf[[i,j]]), collapse = "; ")    
        mybibdf[[i,j]]<-(gsub("(\\{|\\})","", mybibdf[[i,j]]) )
        mybibdf[[i,j]]<-gsub("'","", mybibdf[[i,j]])
        mybibdf[[i,j]]<-gsub("(\\^)","", mybibdf[[i,j]])
        mybibdf[[i,j]]<-gsub("\\\\","", mybibdf[[i,j]])
    }
}
mybibdf[mybibdf=="NA"]<-NA
}

AnyItemIfTitle<-function (vector,xCasted,spaces,dots=1,booltitle){
    xCasted[,setdiff(vector,colnames(xCasted))]<-NA
    for (k in 1){    
        cat(             
                        paste0("  \n  \n", 
                        paste(xCasted[,which(colnames(xCasted) %in% vector[k]  )][i])
                        )
        )# cat
    } 
    if(length(vector)>1) {
    for (k in 2:length(vector)){
        cat(
            
            ifelse(!is.na(xCasted[,which(colnames(xCasted) %in% vector[k]  )][i] ),
                   paste0(paste0(c(rep(".",dots) ), collapse = ""),
                          paste0(c(rep("&nbsp;",spaces) ), collapse = ""), 
                          paste(xCasted[,which(colnames(xCasted) %in% vector[k]  )][i]
                          )
                   )
                   ,"")
        ) # cat
    } # for
    }
}

ItemIfTitleIfSectionIfBold<-function (field,xCasted,boolSection=F,boolBold=F){
  xCasted[,setdiff(field,colnames(xCasted))]<-NA
  for (j in 1:length(field) ){
        cat(
                      ifelse(!is.na(xCasted[,which(colnames(xCasted) %in% field[j]  )][i] ),
                          paste0("  \n"
                                  ,ifelse(boolSection,"  \n## ","")
                                  ,ifelse(boolBold,"__","")
                                  ,paste(xCasted[,which(colnames(xCasted) %in% field[j]  )][i]
                          ),ifelse(boolBold,"__","")  #"__"
                      ), ""
                      ) #ifelse
          ) # cat
  } # for j in field
}

for (i in 1:nrow(mybibdf)){
    AnyItemIfTitle(c("author","title","year","journal","volume","pages","publisher"),mybibdf,1, booltitle = F)
    ItemIfTitleIfSectionIfBold("url",mybibdf)
}
```

# Authors

[Fernando Roa](https://ferroao.gitlab.io/curriculumpu)
<br>
[Mariana PC Telles](http://lattes.cnpq.br/4648436798023532)


